
services:
  node1:
    image: mysql:8.0
    container_name: node1
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: steamgameswarehouse
    ports:
      - "3307:3306" 
    volumes:
      - ./node1_data:/var/lib/mysql
      - ./configs/master.cnf:/etc/mysql/conf.d/my.cnf
      - ./node1_dump.sql:/docker-entrypoint-initdb.d/node1_dump.sql
    networks:
      - db_network
    restart: always

  node2:
    image: mysql:8.0
    container_name: node2
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: steamgameswarehouse
    ports:
      - "3308:3306"  
    volumes:
      - ./node2_data:/var/lib/mysql
      - ./configs/slave.cnf:/etc/mysql/conf.d/my.cnf
      - ./node2_dump.sql:/docker-entrypoint-initdb.d/node2_dump.sql
    networks:
      - db_network
    restart: always

  node3:
    image: mysql:8.0
    container_name: node3
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: steamgameswarehouse
    ports:
      - "3309:3306"  
    volumes:
      - ./node3_data:/var/lib/mysql
      - ./configs/slave2.cnf:/etc/mysql/conf.d/my.cnf
      - ./node3_dump.sql:/docker-entrypoint-initdb.d/node3_dump.sql
    networks:
      - db_network
    restart: always

networks:
  db_network:
    driver: bridge
